name: Smart Contract Deployment

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network to deploy to'
        required: true
        default: 'mumbai'
        type: choice
        options:
          - localhost
          - mumbai
          - polygon
      verify:
        description: 'Verify contract on explorer'
        required: true
        default: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/contracts

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run tests
        run: forge test -vvv

      - name: Deploy to ${{ github.event.inputs.network }}
        run: |
          if [ "${{ github.event.inputs.network }}" = "localhost" ]; then
            forge script script/Deploy.s.sol --rpc-url http://localhost:8545 --broadcast
          elif [ "${{ github.event.inputs.network }}" = "mumbai" ]; then
            forge script script/Deploy.s.sol --rpc-url $MUMBAI_RPC_URL --broadcast --verify
          elif [ "${{ github.event.inputs.network }}" = "polygon" ]; then
            forge script script/Deploy.s.sol --rpc-url $POLYGON_RPC_URL --broadcast --verify
          fi
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          MUMBAI_RPC_URL: ${{ secrets.MUMBAI_RPC_URL }}
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-${{ github.event.inputs.network }}
          path: |
            broadcast/
            out/
